### ISSUE TITLE
CST inverse id function

### ISSUE THREAD

**Issue by shoshanan** [simongog/sdsl#17]
We have an application that requires the functionality of mapping a node id to a node object.  We hope you can implement it so that is also takes constant time and no extra space.

Thank you,
Shoshana

**Comment by simongog** [comment]
Which CST are you using? cst_sada or cst_sct3?
I will add a method inv_id(size_type) such that for a node v we have inv_id(id(v))=v.

A constant time solution for cst_sada would require an additional sublinear data structure (rank on the bitpattern 11 with overlaps). A easier solution takes log(size()) time.

**Comment by shoshanan** [comment]
I began by using cst_sct3 but now that I'm running the program on different data sets, I am using several different CSTs.  I would like to use cst_sada as well.

**Comment by simongog** [comment]
The feature is now implemented for `cst_sct3` and `cst_sada` class in the ''inverse_id_for_cst'' branch:
https://github.com/simongog/sdsl/tree/inverse_id_for_cst

I have tested the implementation with medium sizes test cases.
Unfortunately the time complexity is only log(n) in for inner nodes right now and 
constant for leaves.
To make the complexity constant in both cases, I would have to add select_data structures.
But this would affect the backward compatibility of the library.

**Comment by shoshanan** [comment]
Is the time complexity O(log n) for inner nodes in both cst_sct3 and cst_sada or only for cst_sada?

How should I update the library that I installed?  Are there particular files that I should download?

Thank you!

**Comment by simongog** [comment]
If you have not cloned the repository start with
(1) `git clone git://github.com/simongog/sdsl.git`
otherwise in your sdsl directory make
(1) `git pull`

and the go into the sdsl directory and checkout the new branch with your feature
(2) `cd sdsl`
(3) `git checkout -t origin/inverse_id_for_cst`
(4) `cd build`
(5) `./build.sh`

**Comment by simongog** [comment]
is tested and available in the development branch
