### ISSUE TITLE
cst_sct3 does not have a swap() function implemented.

### ISSUE THREAD

**Issue by mpetri** [simongog/sdsl#18]
no swap function means I can't use util::clear() to free the memory.

**Comment by simongog** [comment]
That's a tricky thing to write, since I have to add an additional function to the lcp-classes.
Can you survive a few days without it?

**Comment by mpetri** [comment]
sure. I'm just reporting it to let you know.

On Tue, May 22, 2012 at 8:16 PM, Simon Gog
reply@reply.github.com
wrote:

**Comment by simongog** [comment]
The feature is now available in the development branch. Cheers.
