### ISSUE TITLE
init() methods or support data structure will be removed

### ISSUE THREAD

**Issue by simongog** [simongog/sdsl#20]
In addition to the constructor a support data structure provide also a `init` method.
Since now all support data structure provide a swap operator the init method is
superfluous, since we can replace the old code completely with the constructor and the swap operation:
E.g.

``` c++
bit_vector b;
rank_support_v<> b_rank;
...
b_rank(&b);
```

can be replaced with

``` c++
bit_vector b;
rank_support_v<> b_rank;
...
{
  rank_support_v<> temp(&b);
  b_rank.swap(temp);
  b_rank.set_vector(&b);
}
```

To simplify the process, I have added a method util::init_support(S &s, P *p)
and so the example now looks like this 

``` c++
bit_vector b;
rank_support_v<> b_rank;
...
util::init_support(b_rank, &b);
```

and we don't have to implement init methods for support data structures in the future.

**Comment by mpetri** [comment]
this will break a lot of code "deployed" by other users though.

**Comment by simongog** [comment]
Ok, first it is marked as deprecated. I have changed all pieces in the library to the new style already. It is not much work. Just a grep for "([^ ]).init(.*)" and changing `b_rank.init(v)` to `util::init_support(v, b_rank)` can also done with a regular expression.  
I have also fixed many swap operators and added tests.
