### ISSUE TITLE
lcp_construct.cpp line 480 - dynamic size array on stack

### ISSUE THREAD

**Issue by mpetri** [simongog/sdsl#23]
lcp_construct.cpp in function construct_lcp_simple_5n() line 480: size_type queries[sigma];

sigma is not known at compile time so I think the queries array should be on the heap?

**Comment by simongog** [comment]
You're right. I have used a GNU extension.
http://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Variable-Length.html#Variable-Length
I have fixed it now.
